pragma Singleton
import QtQuick

QtObject {
    property color foreground: "#f0dede"
    property color background: "#1a1111"
    property color cursor: "#f0dede"
    property color primary: "#ffb3b5"
    property color primaryForeground: "#561d22"
    property color secondary: "#e6bdbd"
    property color secondaryForeground: "#44292a"
    property color tertiary: "#e6c08d"
    property color tertiaryForeground: "#432c05"
    property color surface: "#1a1111"
    property color surfaceBright: "#413737"
    property color error: "#ffb4ab"
    property color errorDim: "#ff8678"
    property color errorForeground: "#690005"
    property color errorContainer: "#93000a"
    property color outline: "#9f8c8c"
    property color shadow: "#000000"
    property color red: "#ffb3af"
    property color redDim: "#ff837c"
    property color green: "#b7d085"
    property color greenDim: "#a1c260"
    property color yellow: "#dec56e"
    property color yellowDim: "#d5b444"
    property color blue: "#cebdfe"
    property color blueDim: "#a98bfd"
    property color magenta: "#fcb0d5"
    property color magentaDim: "#fa7fbb"
    property color cyan: "#82d3e2"
    property color cyanDim: "#59c4d8"
    property color white: "#82d3e0"
}